### ISSUE TITLE
OCP 4.16 SILVER Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [bcgov/developer-experience#5347]
**Describe the epic**
Epic to track all work upgrading SILVER to OCP 4.16.

**Additional context**
CHG for SILVER 

**Definition of done**
- [x] Execute CHG for Registry Prune
- [x] Execute CHG for OCP upgrade and firmware updates
- [x] SILVER upgraded to OCP 4.16

**Comment by tbaker1313** [comment]
Completed.
