### ISSUE TITLE
OCP 4.16 GOLD Upgrade Epic

### ISSUE THREAD

**Issue by StevenBarre** [bcgov/developer-experience#5351]
**Describe the epic**
Epic to track all work upgrading GOLD to OCP 4.16.

**CHANGES**
CHG for GOLD

**Definition of done**
- [x] Execute CHG for OCP upgrade prep
- [x] Execute CHG for OCP upgrade
- [x] GOLD upgraded to OCP 4.16
