### ISSUE TITLE
Virtual to Physical migration - 19 new servers

### ISSUE THREAD

**Issue by lukegonis** [bcgov/developer-experience#5489]
**Describe the issue**

**What is the Value/Impact?**

**What is the plan? How will this get completed?**
***REQ0169782***
- [x] RITM0196630 mcs-golddr-app-22.dmz replaces app-08 app-09
- [x] RITM0196631 mcs-golddr-app-23.dmz replaces app-10 app-11
- [x] RITM0196632 mcs-golddr-app-24.dmz replaces app-12 app-13
- [x] RITM0196633 mcs-golddr-app-25.dmz replaces app-14 app-15
- [x] RITM0196634 mcs-golddr-app-26.dmz replaces app-16 app-17
- [x] RITM0196635 mcs-golddr-app-27.dmz replaces app-18 app-19
- [x] RITM0196636 mcs-clab-app-05.dmz replaces app-01
- [x] RITM0196637 mcs-clab-app-06.dmz replaces app-02
- [x] RITM0196638 mcs-clab-app-07.dmz replaces app-03
- [x] RITM0196639 mcs-clab-app-08.dmz replaces app-04

***REQ0169790***
- [x] RITM0196647 mcs-gold-app-14.dmz replaces app-08 app-09
- [x] RITM0196648 mcs-gold-app-15.dmz replaces app-10
- [x] RITM0196649 mcs-silver-app-95.dmz replaces app-57 app-58
- [x] RITM0196650 mcs-silver-app-89.dmz replaces app-45 app-46
- [x] RITM0196651 mcs-silver-app-90.dmz replaces app-47 app-48
- [x] RITM0196652 mcs-silver-app-91.dmz replaces app-49 app-50
- [x] RITM0196653 mcs-silver-app-92.dmz replaces app-51 app-52
- [x] RITM0196654 mcs-silver-app-93.dmz replaces app-53 app-54
- [x] RITM0196655 mcs-silver-app-94.dmz replaces app-55 app-56

**Identify any dependencies**
Internal, external, who to contact in case of absence, person to refer to for further help.

**Definition of done**
Describe what 'complete' will look like.

**Comment by wmhutchison** [comment]
Work In Progress for six new physical APP servers in SILVER (MCS-SILVER-APP-89.DMZ through MCS-SILVER-APP-94.DMZ). Currently dealing with hardware issues on one of the new servers, expecting that to be resolved today. Network QA almost complete, and should have internal prep finished in the next two business days, meaning server builds can start the week of January 6th.

**Comment by wmhutchison** [comment]
Creating a checklist for the current six nodes in progress. These nodes will remain quarantined once done and not in service, that will happen later when the matching decomm tickets for VMs drop and we're not in the middle of any OCP upgrade work in SILVER.

- [ ] MCS-SILVER-APP-89.DMZ
- [ ] MCS-SILVER-APP-90.DMZ
- [ ] MCS-SILVER-APP-91.DMZ
- [ ] MCS-SILVER-APP-92.DMZ
- [ ] MCS-SILVER-APP-93.DMZ
- [ ] MCS-SILVER-APP-94.DMZ

As part of this, additional internal work will be completed in advance as well (update CI contact/technical details, etc). That way when we're ready to move forward with decomm of VMs and go-live of replacement physicals, it can happen quickly.

**Comment by wmhutchison** [comment]
Converting this ticket into an Epic. Will then assign appropriate tickets to this one specific to each chunk of work as it drops.

**Comment by StevenBarre** [comment]
REQ0169782
RITM0196630 mcs-golddr-app-22.dmz replaces app-08 app-09
RITM0196631 mcs-golddr-app-23.dmz replaces app-10 app-11
RITM0196632 mcs-golddr-app-24.dmz replaces app-12 app-13
RITM0196633 mcs-golddr-app-25.dmz replaces app-14 app-15
RITM0196634 mcs-golddr-app-26.dmz replaces app-16 app-17
RITM0196635 mcs-golddr-app-27.dmz replaces app-18 app-19
RITM0196636 mcs-clab-app-05.dmz replaces app-01
RITM0196637 mcs-clab-app-06.dmz replaces app-02
RITM0196638 mcs-clab-app-07.dmz replaces app-03
RITM0196639 mcs-clab-app-08.dmz replaces app-04

REQ0169790
RITM0196647 mcs-gold-app-14.dmz replaces app-08 app-09
RITM0196648 mcs-gold-app-15.dmz replaces app-10
RITM0196649 mcs-silver-app-95.dmz replaces app-57 app-58
RITM0196650 mcs-silver-app-89.dmz replaces app-45 app-46
RITM0196651 mcs-silver-app-90.dmz replaces app-47 app-48
RITM0196652 mcs-silver-app-91.dmz replaces app-49 app-50
RITM0196653 mcs-silver-app-92.dmz replaces app-51 app-52
RITM0196654 mcs-silver-app-93.dmz replaces app-53 app-54
RITM0196655 mcs-silver-app-94.dmz replaces app-55 app-56
